version: "3"

services:
  jupyterlab:
    image: ccr.ccs.tencentyun.com/ggicci/jupyter:latest
    container_name: jupyterlab
    restart: unless-stopped
    expose:
      - 80
    volumes:
      - "./data:/app"
    logging:
      options:
        max-size: "10M"
        max-file: "7"
