version: "3"

services:
  jupyter:
    image: ccr.ccs.tencentyun.com/ggicci/jupyter:latest
    container_name: jupyter
    restart: unless-stopped
    environment:
      - "TZ=Asia/Shanghai"
      - "SHELL=/bin/bash"
    expose:
      - 80
    volumes:
      - "./data:/app"
    logging:
      options:
        max-size: "10M"
        max-file: "7"

