version: "3"

services:
  jupyter:
    image: ccr.ccs.tencentyun.com/ggicci/jupyter:latest
    container_name: jupyter
    restart: unless-stopped
    environment:
      - "TZ=Asia/Shanghai"
      - "SHELL=/bin/bash"
    ports:
      - "8888:80"
    volumes:
      - "./jupyter_lab_config.py:/etc/jupyter/jupyter_lab_config.py"
      - "./data:/app"
    command: ["lab"]
    logging:
      options:
        max-size: "10M"
        max-file: "7"
